version: '3.0'
services:
  # Container for ROS2 rtabmap
  unitree:
    # Build or Reference the image
    build: .
    image: assume/unitree
    container_name: ros2-unitree
    stdin_open: true
    tty: true
    privileged: true
    command: bash
    network_mode: host
    working_dir: /home/user

    # Container Settings    
    environment:
      - DISPLAY=${DISPLAY}
      # Set ros2 environment variables.
      # References:
      # - https://docs.ros.org/en/humble/Concepts/Intermediate/About-Domain-ID.html
      # - https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Configuring-ROS2-Environment.html
      # - https://docs.ros.org/en/humble/Tutorials/Demos/Logging-and-logger-configuration.html#console-output-colorizing
      - ROS_LOCALHOST_ONLY=0
      - ROS_DOMAIN_ID=0
      - RCUTILS_COLORIZED_OUTPUT=1
      # If you want to access GPU, please uncomment the lines below.
      # Reference : https://docs.docker.com/compose/gpu-support/
      # deploy:
      #   resources:
      #     reservations:
      #       devices:
      #         - driver: nvidia
      #           count: all
      #           capabilities: [ gpu ]
    volumes:
      # Mount local timezone into container. ( Readonly )
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - ../:/home/user/workspace